name: task_04
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  json_annotation: ^4.6.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  pedantic_mono: any

flutter:
  uses-material-design: true
